name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: Build Output
        path: dist
    - run: npm run docs
    - uses: actions/upload-artifact@v2
      with:
        name: API Docs
        path: dist/docs
    - run: npm run rollup
    - uses: actions/upload-artifact@v2
      with:
        name: Browser Output
        path: dist/browser
    - run: npm test
      env:
        CI: true